# Generated by Django 5.2.8 on 2026-03-13 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('selected_plan', models.CharField(choices=[('Starter', 'Starter - ₹19,999/m'), ('Growth', 'Growth - ₹39,999/m'), ('Scale', 'Scale - ₹49,999/m'), ('Domination', 'Domination - ₹74,999/m'), ('Normal Website', 'Normal Website - ₹6,000'), ('E-commerce Website', 'E-commerce Website - ₹10,000'), ('Logo + Branding', 'Logo + Branding - ₹15,000-₹20,000'), ('Photography Only', 'Photography Only - ₹20,000'), ('Photo + Video Package', 'Photo + Video Package - ₹25,000-₹35,000')], max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
